/**
 * Slug-uri vechi -> slug-uri noi, pentru 301.
 *
 * Generat de `scripts/fix-mangled-slugs.ts`. Nu se editeaza de mana.
 *
 * Slug-urile stricate la import (diacritice sterse, ramasite de entitati HTML)
 * apucasera sa se claseze in Google, deci redenumirea singura ar fi rupt niste
 * pozitii deja castigate. Middleware-ul citeste harta si raspunde 301.
 */
export const SLUG_REDIRECTS: Record<string, string> = {
  "abibilduri-snep-medii-roii-7-buc": "abtibilduri-snep-medii-rosii-7-buc",
  "abibilduri-snep-ndash-mici-roii-7-buc": "abtibilduri-snep-mici-rosii-7-buc",
  "after-sun-crem-de-corp-dup-plaj-iluminatoare-hidratant": "after-sun-crema-de-corp-dupa-plaja-iluminatoare-hidratanta",
  "agitator-mare-cu-praf-i-suport-pentru-capsule": "agitator-mare-cu-praf-si-suport-pentru-capsule",
  "aloe-glucozamin": "aloe-glucozamina",
  "balsam-de-pr-restructurant": "balsam-de-par-restructurant",
  "beisoare-din-bambus-odorizant-camer-250ml": "betisoare-din-bambus-odorizant-camera-250ml",
  "belove-spun-intim": "belove-sapun-intim",
  "brri-snep-costiquellochecosti-cu-diverse-culori": "bratari-snep-costiquellochecosti-cu-diverse-culori",
  "cacao-de-protein-de-rice-i-lupine-vegan": "cacao-de-proteina-de-rice-si-lupine-vegan",
  "cafea-solubil-special-cu-ganoderma": "cafea-solubila-speciala-cu-ganoderma",
  "capsule-de-cafea-cu-oleuropein-compatibile-cu-nespresso": "capsule-de-cafea-cu-oleuropeina-compatibile-cu-nespresso",
  "cciul-de-iarn-neagr": "caciula-de-iarna-neagra",
  "cciul-de-iarn-neagr-cu-pompon": "caciula-de-iarna-neagra-cu-pompon",
  "cciul-de-iarn-roie": "caciula-de-iarna-rosie",
  "creatin": "creatina",
  "crem-anticelulitic-adipozitate": "crema-anticelulitica-adipozitate",
  "crem-de-corp-hidratant": "crema-de-corp-hidratanta",
  "crem-de-noapte-pentru-fa-anti-age": "crema-de-noapte-pentru-fata-anti-age",
  "crem-de-protecie-solar-pentru-fa-i-decolteu-spf-50": "crema-de-protectie-solara-pentru-fata-si-decolteu-spf-50",
  "crem-gel-aftershave-cu-efect-de-calmare": "crema-gel-aftershave-cu-efect-de-calmare",
  "crem-pentru-fa-de-zi-biostimulatoare": "crema-pentru-fata-de-zi-biostimulatoare",
  "cup-snep": "cupa-snep",
  "earfa-de-easeline": "esarfa-de-easeline",
  "fanfresh-past-de-dini": "fanfresh-pasta-de-dinti",
  "geant-frigorific-suncare": "geanta-frigorifica-suncare",
  "geant-suncare": "geanta-suncare",
  "gel-de-du": "gel-de-dus",
  "gel-de-du-reductor-250ml": "gel-de-dus-reducator-250ml",
  "gold-mask-masc-de-aur-peel-off": "gold-mask-masca-de-aur-peel-off",
  "kit-de-igien-bunal": "kit-de-igiena-bunala",
  "masc-reparatoare-dup-plaj": "masca-reparatoare-dupa-plaja",
  "morinda-piugrave": "morinda-piu",
  "oligravever": "oliver",
  "olivograve": "olivo",
  "pants-easeline-brbat-m": "pants-easeline-barbat-m",
  "periu-de-dini-din-bambus": "periuta-de-dinti-din-bambus",
  "plac-de-silicon-pentru-valiz": "placa-de-silicon-pentru-valiza",
  "plus-cacao-i-capsuni-vegane": "plus-cacao-si-capsuni-vegane",
  "promoie-aparat-2espresso-cafea-cu-ganoderma-compatibile-cu-nespresso": "promotie-aparat-2espresso-cafea-cu-ganoderma-compatibile-cu-nespresso",
  "ser-anti-imbatranire-fata-si-d-collet": "ser-anti-imbatranire-fata-si-decollete",
  "ser-pt-conturul-ochilor-i-buzelor": "ser-pt-conturul-ochilor-si-buzelor",
  "snep-ice-masc-anti-galben": "snep-ice-masca-anti-galben",
  "snep-slimfit-brbai-t-thirt-s": "snep-slimfit-barbati-t-thirt-s",
  "sneplumina-masc-hidratant-efect-de-mtase": "sneplumina-masca-hidratanta-efect-de-matase",
  "thegrave-mix": "the-mix",
  "thegrave-mix-plicuri": "the-mix-plicuri",
  "thegrave-peach": "the-peach",
  "trico-salus-solution-loiune-redensifant": "trico-salus-solution-lotiune-redensifanta",
  "tricou-brbai-easeline-m": "tricou-barbati-easeline-m",
  "tricou-snep-brbai-negru-s": "tricou-snep-barbati-negru-s",
  "tricou-snep-brbai-rou-s": "tricou-snep-barbati-rosu-s",
  "vegan-lupine-protein-orange-i-raspberry": "vegan-lupine-protein-orange-si-raspberry",
  "vincigrave": "vinci",
};
